# Joshua Geoghegan
# Smart Hurley - Convert TFLite to Arduino Header (Final)
# 4 classes: idle, swing, impact, fake_hit

# This script reads the TFLite model file and the model info JSON file generated by 2_train_model_final.py,
# and converts the TFLite model into a C header file that can be included in an Arduino sketch. 
# It also extracts the scaler mean and scale values used for normalisation during training,
# and includes them in the header file as constant float arrays. The generated header file contains:
# - The TFLite model as a byte array
# - The scaler mean and scale values as float arrays
# - The class names, number of classes, and number of features as constants
import json

# Configuration
TFLITE_FILE     = "model/hurley_model.tflite"
MODEL_INFO_FILE = "model/model_info.json"
OUTPUT_HEADER   = "model/hurley_model.h"

# Read the TFLite model file as bytes and convert to a C-style byte array, 
# while also reading the model info from the JSON file for use in generating 
# the header content. The header file will be structured to include all necessary information for using 
# the model on an Arduino, including the model data, scaler parameters, and class/feature information.
with open(MODEL_INFO_FILE) as f:
    info = json.load(f)

# Read the TFLite model file as bytes
with open(TFLITE_FILE, "rb") as f:
    tflite_bytes = f.read()

# Convert the TFLite bytes to a C-style byte array string, formatted for inclusion in a header file. Each byte is 
# represented as a hexadecimal value (e.g. 0x1f), and the array is formatted with 12 bytes 
# per line for readability. The resulting string will be used in the
hex_values = [f"0x{b:02x}" for b in tflite_bytes]
rows       = [hex_values[i:i+12] for i in range(0, len(hex_values), 12)]
array_body = "\n".join("  " + ", ".join(row) + "," for row in rows).rstrip(",")

# Helper function to convert a list of floats into a C-style array declaration, which will be 
# used for the scaler mean and scale values.
def floats_to_c(name, values):
    vals = ", ".join(f"{v:.6f}f" for v in values)
    return f"const float {name}[{len(values)}] = {{{vals}}};"

# Generate the header file content, including the TFLite model byte array, scaler parameters, class names, 
# and constants for number of classes and features. The header file is structured to be easily included 
# in an Arduino sketch, allowing for direct use of the model and scaler parameters in the embedded code.
header = f"""// AUTO-GENERATED by 3_convert_to_arduino_final.py
// Smart Hurley TinyML Model
// Classes : idle, swing, impact, fake_hit
// Features: {info['num_features']}
// Size    : {info['model_size_kb']} KB

#ifndef HURLEY_MODEL_H
#define HURLEY_MODEL_H

#include <stdint.h>

const unsigned int  hurley_model_len  = {len(tflite_bytes)};
const unsigned char hurley_model_data[] = {{
{array_body}
}};
// Scaler parameters for normalisation (mean and scale values for each feature)
{floats_to_c("SCALER_MEAN",  info["scaler_means"])}
{floats_to_c("SCALER_SCALE", info["scaler_scales"])}

// Class names and constants for number of classes and features
const char* CLASS_NAMES[] = {{"idle", "swing", "impact", "fake_hit"}};
const int   NUM_CLASSES   = {info['num_classes']};
const int   NUM_FEATURES  = {info['num_features']};

#endif
"""
# Write the generated header content to the output file, and print a summary of the generated model 
# information, including the size of the TFLite model and the classes included. 
# The generated header file can then be copied into an Arduino sketch folder for use in embedded applications.
with open(OUTPUT_HEADER, "w", encoding="utf-8") as f:
    f.write(header)

# Print summary of generated model information, including the size of the TFLite model and the classes included. 
# This provides a quick reference for the user to understand the contents of the generated header file and what to 
# expect when using it in an Arduino sketch.
print(f"Generated: {OUTPUT_HEADER}")
print(f"  Size    : {len(tflite_bytes)} bytes ({info['model_size_kb']:.1f} KB)")
print(f"  Classes : idle, swing, impact, fake_hit")
print(f"\nCopy model/hurley_model.h into your Arduino sketch folder.")
