# Joshua Geoghegan
# Smart Hurley - Convert CNN TFLite to Arduino Header
# 4 classes: idle, swing, impact, fake_hit
#
# This script reads the CNN TFLite model file and the model info JSON file
# generated by 2_train_model_cnn.py, and converts the TFLite model into a
# C header file that can be included in an Arduino sketch.
#
# Unlike the feature-based MLP which uses a StandardScaler on 31 features,
# the CNN operates on raw (100, 6) IMU windows normalised per-channel using
# the mean and standard deviation computed across the training set.
# These channel_means and channel_stds are embedded in the header so the
# Arduino firmware can apply the same normalisation before running inference.

import json
import numpy as np

# Configuration
TFLITE_FILE     = "model/hurley_cnn_model.tflite"
MODEL_INFO_FILE = "model/model_info_cnn.json"
OUTPUT_HEADER   = "model/hurley_cnn_model.h"

# Load model info 
# We read the model information from the JSON file generated during training, which contains details about the model 
# architecture, input shape, channel names, number of classes, label names, channel means and standard deviations used for normalization
# and the size of the saved model in kilobytes. This information will be used to generate the C header file with the appropriate constants and arrays.
with open(MODEL_INFO_FILE) as f:
    info = json.load(f)

# Read TFLite binary 
# We open the TFLite model file in binary read mode and read its contents into a byte string called tflite_bytes. 
# This byte string will be converted into a C byte array for inclusion in the header file.
with open(TFLITE_FILE, "rb") as f:
    tflite_bytes = f.read()

# Convert to C byte array 
# We convert the TFLite model byte string into a list of hexadecimal string representations of each byte, formatted as "0xXX". 
# We then group these hexadecimal values into rows of 12 for better readability in the generated C array. 
hex_values = [f"0x{b:02x}" for b in tflite_bytes]
rows       = [hex_values[i:i+12] for i in range(0, len(hex_values), 12)]
# We join the rows into a single string with proper indentation and commas, and remove the trailing comma from the last row.
array_body = "\n".join("  " + ", ".join(row) + "," for row in rows).rstrip(",")

# Helper: float list to C array
# We define a helper function floats_to_c that takes a name and a list of float values, and returns a string containing 
# a C declaration of a constant float array with the given name and values formatted to 6 decimal places. This function will 
# be used to generate the CHANNEL_MEAN and CHANNEL_STD arrays in the header file.
def floats_to_c(name, values):
    vals = ", ".join(f"{v:.6f}f" for v in values)
    return f"const float {name}[{len(values)}] = {{{vals}}};"

# Generate header 
# We extract the channel means, channel standard deviations, window size, and number of channels from the model information dictionary. 
# These values will be used to populate the constants and arrays in the generated C header file. The window size and number of channels 
# are derived from the input shape of the model, which is expected to be (100, 6) for this CNN.
channel_means = info["channel_means"]
channel_stds  = info["channel_stds"]
window_size   = info["input_shape"][0]   # 100
num_channels  = info["input_shape"][1]   # 6

# We create a multi-line string called header that contains the contents of the C header file to be generated. This string includes comments describing the model, 
# the necessary include statements, the declaration of the TFLite model data as a byte array, the normalisation parameters for each channel 
# and constants for the class names, number of classes, window size, and number of channels. The CHANNEL_MEAN and CHANNEL_STD 
# arrays are generated using the floats_to_c helper function.
header = f"""// AUTO-GENERATED by 3_convert_to_arduino_cnn.py
// Smart Hurley TinyML CNN Model
// Architecture : 1D CNN
// Input shape  : ({window_size}, {num_channels})  ->  raw IMU window (ax, ay, az, gx, gy, gz)
// Classes      : idle, swing, impact, fake_hit
// Size         : {info['model_size_kb']} KB

#ifndef HURLEY_CNN_MODEL_H
#define HURLEY_CNN_MODEL_H

#include <stdint.h>

// Model data 
// We declare a constant unsigned integer hurley_model_len that holds the length of the TFLite model byte array 
// and a constant unsigned char array hurley_model_data that contains the hexadecimal byte values of the TFLite model.
const unsigned int  hurley_model_len    = {len(tflite_bytes)};
const unsigned char hurley_model_data[] = {{
{array_body}
}};

// Normalisation parameters (per channel: ax, ay, az, gx, gy, gz)
// Apply before inference: normalised = (raw - CHANNEL_MEAN[i]) / CHANNEL_STD[i]
{floats_to_c("CHANNEL_MEAN", channel_means)}
{floats_to_c("CHANNEL_STD",  channel_stds)}

// Model constants 
const char* CLASS_NAMES[] = {{"idle", "swing", "impact", "fake_hit"}};
const int   NUM_CLASSES   = {info['num_classes']};
const int   WINDOW_SIZE   = {window_size};
const int   NUM_CHANNELS  = {num_channels};

#endif // HURLEY_CNN_MODEL_H
"""

# Write header file 
with open(OUTPUT_HEADER, "w", encoding="utf-8") as f:
    f.write(header)

# We print the filename of the generated header file, along with details about the model size, input shape, and classes. 
# We also provide instructions for copying the generated header file into the Arduino sketch folder and updating the firmware to
print(f"Generated : {OUTPUT_HEADER}")
print(f"  Size    : {len(tflite_bytes)} bytes ({info['model_size_kb']:.1f} KB)")
print(f"  Input   : ({window_size}, {num_channels}) raw IMU window")
print(f"  Classes : idle, swing, impact, fake_hit")
print(f"\nCopy model/hurley_cnn_model.h into your Arduino sketch folder.")
print("Update firmware: buffer size 100, use CHANNEL_MEAN/STD for normalisation.")
